### ISSUE TITLE
Fork repo?

### ISSUE THREAD

**Issue by d0mme-zz** [lgs/paymill_on_rails#1]
Hi,

I'm a guy from dev team from Paymill. Can we fork your repo and name you on our page? :)

**Comment by lgs** [comment]
Sure, I would be glad  ;-)

**Comment by d0mme-zz** [comment]
Hi,

sorry about delay, but right now I'm in trouble of work, but didn't forget your repo. Do you have Skype or IRC channel?

Best,
Dominic

**Comment by lgs** [comment]
No worries about delay,
the best chance to reach me is via google chat/email at
luca.soave@gmail.com

bye
Luca
