### ISSUE TITLE
Associate plans subscriptions with users

### ISSUE THREAD

**Issue by zamith** [lgs/paymill_on_rails#4]
Hey Luca,

What do you think of associating subscriptions with users? You could assume there is a `current_user` method, and allow the user to configure that if there isn't one.

It seems odd to create a subscription that are not linked to a user.

Also, you're always creating a client in order to create a subscription. That definitely needs to change, if you want to add subscription edition.  

What do you think?

Thanks.

**Comment by lgs** [comment]
Hi Luís, that's something really missing, I know. 

I currently do not have the time to work on that, anyway i like the way a similar project targeted on Stripe,  implemented via generator "rails g koudoku:install user". 

Please have a look at : 

<pre>
# Update the owner relationship.
gsub_file "app/models/#{subscription_owner_model}.rb", /ActiveRecord::Base/, "ActiveRecord::Base\n\n # Added by Koudoku.\n has_one :subscription\n\n"
</pre>

into [**koudoku project**](https://github.com/andrewculver/koudoku/blob/master/lib/generators/koudoku/install_generator.rb)

Remember that paymill_on_rails is a Rails engine, it's gonna be mounted on a "hosting Rails app" which can have it's own models and I didn't want to clutter users model and name spaces between Rails and his engine.

That said, I'll be happy to merge your pull request eventually, if you gonna take a similar way.

... please, see that your previous pull request [**7112f75**] add ruby "2.0.0" specific heroku syntax, which doesn't work outside that env. That way I'd leave it at "host rails app Gemfile level" not at "Egine level" (we'll be up to rails host deploy on heroku or elseware). In the meanwhile .ruby-version value should be for a feature [**travis-ci**](https://travis-ci.org/lgs/paymill_on_rails)

**Comment by zamith** [comment]
@lgs You could do the same thing as devise and forem, which are also engines. They just assume there is a controller level method which returns a user, and that it's called `current_user`. If it is not, you can configure it. It seems a very practical approach.

As for the ruby version, I'll remove it, no problem.

**Comment by lgs** [comment]
@zamith   I agree with you on devise/forem way, it could be even better approach. Is there any chance for you to pull a request on that innancement ? I'll be happy to merge it.
